feat(stdlib): self-stabilizing gossip algorithm
Collektive/collektive pull request #527
Opened 2024-10-22 15:22 UTC by angelacorte

2024-10-28 20:52 UTC, nicolasfara requested changes

2024-10-28 20:52 UTC, nicolasfara commented on stdlib/src/commonMain/kotlin/it/unibo/collektive/stdlib/Gossip.kt
> + * and updates its value based on the best value received according to the [selector]. uik
```suggestion
 * and updates its value based on the best value received according to the [selector].
```

2024-10-28 20:52 UTC, nicolasfara commented on stdlib/src/commonMain/kotlin/it/unibo/collektive/stdlib/Gossip.kt
> +                comparison == 0 -> listOf(current, next).minBy { it.path.size }
```suggestion
            val candidateValue = selector.compare(current.best, actualNext.best)
            when {
                candidateValue > 0 -> current
                candidateValue == 0 -> listOf(current, next).minBy { it.path.size }
```

2024-10-28 20:52 UTC, nicolasfara commented on stdlib/src/commonMain/kotlin/it/unibo/collektive/stdlib/Gossip.kt
> +        result.copy(local = initial, path = result.path + localId)
Why a copy instead of a new object creation? usually, I try to avoid using `copy` method on `data class`es

2024-10-28 20:52 UTC, nicolasfara commented on stdlib/src/commonMain/kotlin/it/unibo/collektive/stdlib/Gossip.kt
> +data class GossipValue<ID : Comparable<ID>, Value>(
If it is used only locally to the implementations, set it as `private`

2024-10-31 16:49 UTC, DanySK requested changes

2024-11-04 17:27 UTC, DanySK requested changes

2024-11-04 17:27 UTC, DanySK commented on stdlib/src/commonMain/kotlin/it/unibo/collektive/stdlib/Gossip.kt
> +    /**
```suggestion
    /*
```

2024-11-04 17:27 UTC, DanySK commented on stdlib/src/commonMain/kotlin/it/unibo/collektive/stdlib/Gossip.kt
> +fun <ID : Comparable<ID>> Aggregate<ID>.isHappeningGossip(
```suggestion
fun <ID : Comparable<ID>> Aggregate<ID>.isHappeningAnywhere(
```

2024-11-04 17:27 UTC, DanySK commented on stdlib/src/commonMain/kotlin/it/unibo/collektive/stdlib/NonSelfStabilizingGossip.kt
> +fun <ID : Any> Aggregate<ID>.everHappenedGossip(
```suggestion
fun <ID : Any> Aggregate<ID>.everHappened(
```

2024-11-04 17:27 UTC, DanySK commented on stdlib/src/commonMain/kotlin/it/unibo/collektive/stdlib/NonSelfStabilizingGossip.kt
> +fun <ID : Any, Type> Aggregate<ID>.nonSelfStabilizingGossip(
From the user side this is very confusing. Let us create two objects:

`SelfStabilizingGossip`

and

`NonSelfStabilizingGossip`

2024-11-04 17:27 UTC, DanySK commented on stdlib/src/commonTest/kotlin/it/unibo/collektive/stdlib/test/GossipTest.kt
> +
```suggestion
```

2024-11-04 17:27 UTC, DanySK commented on stdlib/src/commonTest/kotlin/it/unibo/collektive/stdlib/test/GossipTest.kt
> +
```suggestion
```

2024-11-04 17:27 UTC, DanySK commented on stdlib/src/commonTest/kotlin/it/unibo/collektive/stdlib/test/GossipTest.kt
> +
```suggestion
```

2024-11-04 17:27 UTC, DanySK commented on stdlib/src/commonTest/kotlin/it/unibo/collektive/stdlib/test/GossipTest.kt
> +
```suggestion
```

2024-11-04 17:27 UTC, DanySK commented on stdlib/src/commonTest/kotlin/it/unibo/collektive/stdlib/test/GossipTest.kt
> +
```suggestion
```

2024-11-05 16:48 UTC, DanySK requested changes

2024-11-05 16:48 UTC, DanySK commented on stdlib/src/commonMain/kotlin/it/unibo/collektive/stdlib/Gossip.kt
> +    ): Value {
Add:
```suggestion
    fun <ID : Comparable<ID>, Value: Comparable<Value>> Aggregate<ID>.gossipMax(local: Value): Value =
        gossipMax(local) { a, b -> a.compareTo(b) }
```

and similar for `gossipMin`

I am also convinced that we should not use `ID`s. We should probably also take a UUIDGenerator function in the most general implementation

2024-11-05 18:23 UTC, nicolasfara requested changes

2024-11-06 10:08 UTC, DanySK commented on stdlib/src/commonTest/kotlin/it/unibo/collektive/stdlib/test/GossipTest.kt
> +            gossipMax(localId.toDouble()) { a, b -> a.compareTo(b) } // gossip the max localID in the network
True, but let's test both, as we shouldn't assume any specific implementation. You could run the two algorithms in a pair, and have both min and max in a pair

2024-11-06 15:11 UTC, nicolasfara approved these changes

2024-11-06 16:43 UTC, DanySK approved these changes

2024-11-06 16:43 UTC, merged