Added first introduction part (Aggragate Programming paragraph)
Collektive/collektive pull request #548
Opened 2024-11-07 10:02 UTC by Danix002

Site introduction implementation

2024-11-07 11:41 UTC, nicolasfara commented on site/docs/introduction/Aggregate Programming.md
Avoid names with spaces. Stick to kebab-case for file names in the documentation.

2024-11-07 11:42 UTC, nicolasfara commented on site/yarn.lock
Please do not track this file. I prefer to keep it simple with npm.

2024-11-07 13:32 UTC, angelacorte commented
@Danix002 I suggest not to close PRs, just leave it open and when you'll add a commit on your branch it will refresh automatically.
Or were there other motivations to close it?

2024-11-07 13:36 UTC, Danix002 commented
There is no reason, i made a mistake. Thank you."

2024-11-07 15:04 UTC, DanySK commented
I would suggest organizing the docs with the DIVIO framework

2024-11-07 16:23 UTC, nicolasfara commented
> I would suggest organizing the docs with the DIVIO framework

I've structured the documentation in that way, following: https://docs.divio.com/documentation-system/

2024-11-23 16:07 UTC, angelacorte commented on site/docs/introduction/aggregate-programming.md
> +
same as I said for the constructs
In Collektive we don't call the functions G, C etc, just describe what they do and eventually cite the reference papers.

2024-11-23 16:07 UTC, angelacorte commented on site/docs/introduction/aggregate-programming.md
> +```javascript
same here
why javascript? 
we already have published in the library the gradient and distanceTo functions, see and use that implementation.

2024-11-23 16:14 UTC, angelacorte commented on site/docs/introduction/aggregate-programming.md
> +<div className="centered">
try to avoid using the HTML syntax, try mdx and react's components if it is possible, I think that docusaurus supports them, but double check.

2024-11-28 17:41 UTC, DanySK commented on site/docs/introduction/_category_.json
> +    "description": "(How the library relates to the Aggregate Programming and Field Calculus sections? Answer in two sentences.)"
how *does* the...

2024-12-09 09:28 UTC, angelacorte requested changes

2024-12-09 09:28 UTC, angelacorte commented on site/docs/introduction/aggregate-programming.mdx
> +
Missing some AC applications examples, where can I use AC? What can I achieve with that? (drone swarms, ecc) For Another example look at the first published application of Collektive related to vascular morphogenesis: https://ieeexplore.ieee.org/document/10771167

2024-12-09 13:46 UTC, angelacorte commented on site/static/img/multiple-levels-of-abstraction-ag.png
a little note: when possible align the arrows and don't overlap them

2025-01-13 09:20 UTC, angelacorte requested changes

2025-01-13 09:20 UTC, angelacorte commented on site/docs/tutorials/basic-usage.mdx
> +  In the third step of the code from the first example, the computed values are assigned to molecules. These molecules can be inspected within the data of a selected device, thereby simplifying the d
Molecules and relative concentrations are strictly related to the Alchemist Simulator. 
In the Collektive first-steps documentation, try to avoid them as much as possible because the tool should potentially run also outside the Alchemist environment.

2025-01-13 09:20 UTC, angelacorte commented on site/docs/tutorials/basic-usage.mdx
> +}
Use the suggestions above to fix this code.

2025-01-13 09:20 UTC, angelacorte commented on site/docs/tutorials/basic-usage.mdx
> +  This second example represents a highly simplified demonstration of leader election using the Collektive library.
Explain better what can be observed by the image.

2025-01-13 09:20 UTC, angelacorte commented on site/docs/tutorials/basic-usage.mdx
> +    <img src="/img/basic-usage-second-example-2.png" style={{ maxWidth: '70%' }} />
The network is too dense and displaying the connections in such a network is hard to understand. 
It would be better to reduce its density first and then show the connections.

2025-01-13 09:20 UTC, angelacorte commented on site/docs/tutorials/basic-usage.mdx
> +  </div>
When displaying example images, provide a brief description of what can be seen in them.

2025-03-08 12:02 UTC, nicolasfara requested changes
Reviewed 3/37

2025-03-08 12:02 UTC, nicolasfara commented on site/docs/introduction/aggregate-programming.mdx
> +
```suggestion
Key operators include:  
- **Gradient formation and value propagation**: operations that calculate distance fields and propagate values across the network based on these gradients.
    These operators are crucial for tasks like broadcasting, projection, or region-based computations, where spatial relationships between nodes are important.
- **Cumulative information gathering**: mechanisms for aggregating information along gradients, such as summing values or collecting information towards specific regions of interest.  
- **Flexible temporal decay**: constructs that manage countdown processes or decay functions, enabling time-based coordination that adapts to changing rates or conditions.  
```

As a general suggestion: avoid spaces between list items in MD

2025-03-08 12:02 UTC, nicolasfara commented on site/docs/introduction/aggregate-programming.mdx
> +2. Cortecchia, Pianini, Ciatto and Casadei, "An Aggregate Vascular Morphogenesis Controller for Engineered Self-Organising Spatial Structures".
Use the footnote MD syntax here

2025-03-08 18:15 UTC, angelacorte reviewed
reviewed 11/37; the rest will follow in the coming days.

2025-03-08 18:15 UTC, angelacorte commented on site/docs/tutorials/basic-usage.mdx
> +    val maxValue = neighborValues.max(base = localId)
ok for the division into step to clarify the meaning of the operation, but I would add in another equivalent example the online code, in order to highlight the ease of use and the short syntax.

2025-03-08 18:15 UTC, angelacorte commented on site/docs/intro.md
> +5. [Library Structure](/docs/about-the-structure/)
In the `Tutorial` section, I would place the `Aggregate Operators[..]` section before `Basic Usage` so that we explain the constructs before showing how to use them; otherwise, it might be difficult to follow. @DanySK @nicolasfara what do you think about it?

2025-03-10 11:31 UTC, angelacorte requested changes

2025-03-10 11:31 UTC, angelacorte commented on site/docs/tutorials/basic-usage.mdx
> +This second example represents a highly simplified demonstration of leader election using the Collektive library.
```suggestion
This second example illustrates a variant of leader election implemented with Collektive.
```

2025-03-10 11:31 UTC, angelacorte commented on site/docs/tutorials/basic-usage.mdx
> +In this final example, we extend the previous exercise with the goal of determining the diameter in relation to a source corresponding to the global maximum. To make the exercise more interesting, we
explain better what is the objective of this example, also it is not clear what you mean with the "the diameter in relation to a source etc", provide a more meaningful definition.

2025-03-10 11:31 UTC, angelacorte commented on site/docs/tutorials/dsl-descriptions.mdx
> +
the entire page is not well rendered, it doesn't use the code snippet syntax, fix it and notify me 
moreover, there's no need to write the entire code and especially the field operations, they're all written in the [dsl](https://javadoc.io/doc/it.unibo.collektive/dsl/latest/index.html) and [stdlib](https://javadoc.io/doc/it.unibo.collektive/stdlib/latest/index.html) kdoc, rather link them to the relative page in the kdoc.

in this section it is better to first explain the base constructs, starting from `exchange-exchanging` > `share-sharing` > `neighboring-neighboringViaExchange` > `evolve-evolving`.
explain how they work at high level (e.g. space-time computation ecc), possibly by using clarifying images (you can use the ones you find [here](https://github.com/angelacorte/slides-master-thesis/tree/master/figures))
and then add some easy but meaningful example of use.

2025-03-10 11:31 UTC, angelacorte commented on site/docs/tutorials/stdlib-descriptions.mdx
> +
same comments as in the `aggregate operators` section

2025-03-10 13:25 UTC, angelacorte requested changes

2025-03-21 23:18 UTC, nicolasfara approved these changes

2025-03-22 10:37 UTC, merged