fix(stdlib): non stabilizing gossip implemented with fold instead of hood
Collektive/collektive pull request #579
Opened 2024-11-14 16:49 UTC by angelacorte

2024-11-15 14:39 UTC, nicolasfara approved these changes

2024-11-15 16:33 UTC, DanySK requested changes

2024-11-15 16:33 UTC, DanySK commented on stdlib/src/commonTest/kotlin/it/unibo/collektive/stdlib/test/GossipTest.kt
> +            nonSelfStabilizingGossip(localId) { first, second -> if (first >= second) first else second }
```suggestion
            gossip(localId) { first, second -> if (first >= second) first else second }
```

2024-12-02 15:13 UTC, nicolasfara approved these changes

2024-12-02 15:15 UTC, DanySK approved these changes

2024-12-02 15:41 UTC, merged