Feat/unnecessary use of constructs
Collektive/collektive pull request #668
Opened 2024-12-23 17:29 UTC by FreshMag

closes #573

2025-01-07 10:46 UTC, angelacorte requested changes

2025-01-07 10:46 UTC, angelacorte commented on compiler-plugin/src/main/kotlin/it/unibo/collektive/frontend/checkers/UnnecessaryUseOfConstructs.kt
> +            "it.unibo.collektive.aggregate.api.Aggregate.evolve",
Note that the cases in which a construct can be called by mistake are not limited to just these; there are also `exchanging`, `sharing`, `evolving`, and `neighboringViaExchange`.

2025-01-07 10:46 UTC, angelacorte commented on compiler-plugin-test/src/test/kotlin/it/unibo/collektive/test/UnnecessaryUseOfConstructsSpec.kt
> +                row("neighboring"),
Test also the constructs mentioned below.

2025-01-07 15:02 UTC, FreshMag commented
@angelacorte I've added the other constructs. I've commented checks for `neighboringViaExchange` for now because I've noticed a small bug in my library `subjekt` regarding names. I will fix it soon and then I will push the version without comments.

2025-01-08 10:46 UTC, angelacorte approved these changes

2025-01-08 13:46 UTC, nicolasfara requested changes

2025-01-08 13:46 UTC, nicolasfara commented on compiler-plugin-test/src/test/kotlin/it/unibo/collektive/test/UnnecessaryUseOfConstructsSpec.kt
> +@OptIn(ExperimentalCompilerApi::class)
Is this already needed? Which function requires it?

2025-01-08 13:46 UTC, nicolasfara commented on compiler-plugin/src/main/kotlin/it/unibo/collektive/frontend/checkers/KtDefaultErrorMessagesCollektive.kt
> +                The ''{0}'' construct is not necessary for the given use case.
Could you provide a more clear warning message?

2025-01-08 13:46 UTC, nicolasfara commented on compiler-plugin/src/main/kotlin/it/unibo/collektive/frontend/checkers/UnnecessaryUseOfConstructs.kt
> +            "it.unibo.collektive.aggregate.api.Aggregate.evolving",
Could you move these FQ names into the appropriate object?

2025-01-09 20:01 UTC, nicolasfara approved these changes

2025-01-10 08:31 UTC, merged